#!/usr/bin/env python3

import sys
import yaml
import base64

def decode(val):
  return base64.b64decode(val).decode('utf-8')

def encode(val):
  return base64.b64encode(val.encode('utf-8')).decode('utf-8')

def noop(val):
  return val

if '-d' in sys.argv:
  op=decode
elif '-e' in sys.argv:
  op=encode
else:
  op=noop

contents = sys.stdin.read()
y = yaml.load(contents, Loader=yaml.SafeLoader)

if 'apiVersion' in y:
  print('apiVersion: %s' % y['apiVersion'])

if 'kind' in y:
  print('kind: %s' % y['kind'])

if 'metadata' in y:
  if 'name' in y['metadata']:
    print('metadata:')
    print("  name: '%s'" % y['metadata']['name'])

if 'type' in y:
  print('type: %s' % y['type'])

if 'data' in y:
  print('data:')
  for k in y['data'].keys():
    val=y['data'][k]
    print("  %s: '%s'" % (k, op(val)))
